name: Auto Sync Clean Workflow

on:
  push:
    branches:
      - main   # يشتغل لما يصير push على الفرع الرئيسي
  schedule:
    - cron: "0 */6 * * *"   # يشتغل أوتوماتيكي كل 6 ساعات
  workflow_dispatch:         # يسمحلك تشغله يدويًا من Actions

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # 1. نسخ المستودع الأول (emergent-github-gpt) - للقراءة فقط
      - name: Checkout emergent-github-gpt
        uses: actions/checkout@v3
        with:
          repository: ihilallu-create/emergent-github-gpt
          path: emergent

      # 2. نسخ المستودع الثاني (gpt-pocket-totur-learn) - للكتابة والتخزين
      - name: Checkout gpt-pocket-totur-learn
        uses: actions/checkout@v3
        with:
          repository: ihilallu-create/gpt-pocket-totur-learn
          path: pocket
          token: ${{ secrets.GPT_GITHUB_POCKET_TOTUR_KEY }}

      # 3. عمل مزامنة للملفات
      - name: Sync files
        run: |
          rsync -av --delete emergent/ pocket/ \
          --exclude '.git/' \
          --exclude '.github/workflows/'

      # 4. Commit + Pull + Push
      - name: Commit and Push changes
        run: |
          cd pocket
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Auto-sync from emergent-github-gpt" || echo "No changes to commit"
          git pull --rebase origin main
          git push origin main
