name: Auto Sync Clean Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # 1. نسخ المستودع الأول (emergent-github-gpt)
      - name: Checkout emergent-github-gpt
        uses: actions/checkout@v3
        with:
          repository: ihilallu-create/emergent-github-gpt
          ref: main
          token: ${{ secrets.GH_PAT }}   # ← استخدم PAT بدل المفتاح العادي
          path: emergent

      # 2. نسخ المستودع الثاني (gpt-pocket-totur-learn)
      - name: Checkout gpt-pocket-totur-learn
        uses: actions/checkout@v3
        with:
          repository: ihilallu-create/gpt-pocket-totur-learn
          ref: main
          token: ${{ secrets.GH_PAT }}   # ← نفس الشي هنا
          path: pocket

      # 3. تثبيت المكتبات المطلوبة
      - name: Install dependencies
        run: |
          pip install openai

      # 4. مزامنة الملفات مع استثناء ملفاتنا الخاصة
      - name: Sync files
        run: |
          rsync -av --delete emergent/ pocket/ \
          --exclude '.git/' \
          --exclude '.github/workflows/' \
          --exclude 'gpt_connector.py' \
          --exclude 'input.txt' \
          --exclude 'analysis_results.md'

      # 5. تشغيل سكربت GPT Connector
      - name: Run GPT Connector
        run: |
          cd pocket
          python gpt_connector.py
        env:
          OPENAI_API_KEY: ${{ secrets.GPT_POCKET_TOTUR_KEY }}   # ← عدلنا الاسم هنا

      # 6. Commit + Push
      - name: Commit and Push changes
        run: |
          cd pocket
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Auto-sync and run GPT connector" || echo "No changes to commit"
          git pull --rebase origin main
          git push origin main
