name: Auto Sync from emergent-github-gpt

on:
  schedule:
    - cron: "0 */12 * * *"   # يشتغل كل 12 ساعة تلقائياً
  workflow_dispatch:          # يعطيك خيار تشغيله يدوي إذا حبيت

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target repo (gpt-pocket-totur-learn)
        uses: actions/checkout@v3
        with:
          repository: ihilallu-create/gpt-pocket-totur-learn
          token: ${{ secrets.GPT_GITHUB_POCKET_TOTUR_KEY }}
          path: target

      - name: Checkout source repo (emergent-github-gpt)
        uses: actions/checkout@v3
        with:
          repository: ihilallu-create/emergent-github-gpt
          token: ${{ secrets.GPT_GITHUB_POCKET_TOTUR_KEY }}
          path: source

      - name: Copy updates from source to target
        run: |
          rsync -av --exclude '.git' ./source/ ./target/

      - name: Commit and push changes
        run: |
          cd target
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-sync from emergent-github-gpt" || echo "No changes to commit"
          git push origin main
