name: Auto Sync from emergent-github-gpt (Final)

on:
  schedule:
    - cron: "0 */6 * * *"   # يشتغل كل 6 ساعات
  workflow_dispatch:        # يسمح لك تشغله يدويًا من تبويب Actions

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout emergent repo
        uses: actions/checkout@v3
        with:
          repository: ihilallu-create/emergent-github-gpt
          token: ${{ secrets.GPT_GITHUB_POCKET_TOTUR_KEY }}

      - name: Checkout target repo
        uses: actions/checkout@v3
        with:
          repository: ihilallu-create/gpt-pocket-totur-learn
          token: ${{ secrets.GPT_GITHUB_POCKET_TOTUR_KEY }}
          path: target-repo

      - name: Sync files
        run: |
          rsync -av --exclude '.git' ./ ./target-repo/

      - name: Commit and Push changes
        run: |
          cd target-repo
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "🔄 Auto Sync from emergent-github-gpt" || echo "No changes to commit"
          git push
