name: Auto Commit to GitHub

on:
  push:
    branches:
      - main

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Auto-commit files
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Auto-commit by GitHub Action" || echo "No changes to commit"
          git push
