name: OpenAI smoke test

on:
  workflow_dispatch:

jobs:
  call-openai:
    runs-on: ubuntu-latest
    steps:
      - name: Call OpenAI models endpoint
        run: |
          echo "📡 Calling OpenAI API..."
          response=$(curl -s https://api.openai.com/v1/models \
            -H "Authorization: Bearer ${{ secrets.GPT_POCKET_TOTUR_KEY }}" \
            -H "Content-Type: application/json")

          echo "✅ Response from OpenAI:"
          echo "$response"
